== Data Piutang Berdasarkan Kode Wilayah

Simpul ini memberikan daftar rincian seluruh data ketetapan untuk tiap Nomor Objek Pajak (NOP) Pajak Bumi dan Bangunan Perdesaan dan Perkotaan (PBB-P2).

=== _Endpoint_ dan _Methods_

----
POST /sismiop-service/desa/get-all-data-current-year
----

=== _Parameters_

==== _Request Parameters_

* `kodeWilayah`: String, kode wilayah lengkap dari Desa/Kelurahan ada di dalam _body request_ tanpa format apapun

==== _Response Parameters_

`List` data dengan elemen seperti berikut :

* `nop`: Nomor Objek Pajak 
* `namaWp`: Nama Wajib Pajak
* `thnPajak`: Tahun Pajak
* `pbb`: Besarnya pokok pajak terhutang
* `statusPemmbayaran`: status pembayaran, bila berisi `1` maka tagihan telah terbayar, bila berisi `0` belum terbayar
* `tglJatuhTempo`: tanggal jatuh tempo untuk pajak terhutang objek tersebut

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-all-data-current-year
----

_body_ :

----
3329010001
----

=== _Response Example_

----
[
  {
    "nop": "332901000100100010",
    "namaWp": "SUKARTA",
    "thnPajak": "2021",
    "pbb": 50000,
    "statusPembayaran": "1",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332901000100100020",
    "namaWp": "SUKARTA",
    "thnPajak": "2021",
    "pbb": 21500,
    "statusPembayaran": "1",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332901000100100030",
    "namaWp": "WARSUKI",
    "thnPajak": "2021",
    "pbb": 15000,
    "statusPembayaran": "1",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332901000100100040",
    "namaWp": "WARSUKI",
    "thnPajak": "2021",
    "pbb": 18200,
    "statusPembayaran": "1",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  ...
]
----



== Data Piutang Untuk Tahun Pajak Tertentu

Simpul ini memberikan daftar rincian untuk seluruh objek yang belum terbayar di suatu wilayah Desa/Kelurahan tertentu dan di tahun pajak tertentu.

=== _Endpoint_ dan _Methods_

----
POST /sismiop-service/desa/get-unpaid-data-by-year
----

=== _Parameters_

==== _Request Parameters_

Berbentuk JSON dengan elemen :

* `kodeWilayah`: String, kode wilayah lengkah dari Desa/Kelurahan
* `thnPajak`: String, tahun pajak 

==== _Response Parameters_

`List` data dengan elemen tiap objeknya seperti berikut :

* `nop`: nomor objek pajak
* `namaWp`: nama wajib pajak
* `thnPajak`: tahun pajak
* `pbb`: besaran pokok yang terhutang
* `statusPembayaran`: status pembayaran tagihan
* `tglJatuhTempo`: tanggal jatuh tempo pembayaran untuk objek tersebut

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-unpaid-data-by-year
----

_body_ :

----
{
    "kodeWilayah": "3329160016",
    "thnPajak": "2021"
}
----

=== _Response Example_

----
[
  {
    "nop": "332916001600100010",
    "namaWp": "SUPARMI",
    "thnPajak": "2021",
    "pbb": 58320,
    "statusPembayaran": "0",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332916001600100020",
    "namaWp": "WALEM BIN TANYA",
    "thnPajak": "2021",
    "pbb": 58380,
    "statusPembayaran": "0",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332916001600100030",
    "namaWp": "TOHIDIN TARNINGSIH",
    "thnPajak": "2021",
    "pbb": 43060,
    "statusPembayaran": "0",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332916001600100040",
    "namaWp": "SLAMET NURIDIN",
    "thnPajak": "2021",
    "pbb": 75860,
    "statusPembayaran": "0",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  ...
]
----



== Data Terbayar Untuk Tahun Pajak Tertentu

Simpul ini memberikan daftar rincian untuk seluruh objek yang telah terbayar berdasarkan ketetapannya di wilayah Desa/Kelurahan tertentu dan untuk tahun pajak tertentu, tidak termasuk denda administrasi bila ada.

=== _Endpoint_ dan _Methods_

----
POST /sismiop-service/desa/get-paid-data-by-wilayah-and-year
----

=== _Parameters_

==== _Request Parameters_

Objek dengan format JSON dengan elemen berikut :

* `kodeWilayah`: kode wilayah Desa/Kelurahan lengkap dari kode Provinsi.
* `thnPajak`: tahun pajak

==== _Response Parameters_

`List` objek dengan elemen tiap objeknya seperti berikut :

* `nop`: nomor objek pajak
* `namaWp`: nama wajib pajak
* `thnPajak`: tahun pajak
* `pbb`: nilai pokok pajak bumi dan bangunan perdesaan dan perkotaan
* `statusPembayaran`: status pembayaran, bila berisi `0` maka objek pajak belum bayar, bila `1` maka objek pajak telah terbayar
* `tglJatuhTempo`: tanggal jatuh tempo pembayaran

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-paid-data-by-wilayah-and-year
----

_body_ : 

----
{
    "kodeWilayah": "3329010009",
    "thnPajak": "2021"
}
----

=== _Response Example_

----
[
  {
    "nop": "332901000900100010",
    "namaWp": "SUTISNO",
    "thnPajak": "2021",
    "pbb": 40000,
    "statusPembayaran": "1",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332901000900100020",
    "namaWp": "RATINAH CS TRIYANTO",
    "thnPajak": "2021",
    "pbb": 28000,
    "statusPembayaran": "1",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  },
  {
    "nop": "332901000900100030",
    "namaWp": "RATINAH CS TRIYANTO",
    "thnPajak": "2021",
    "pbb": 32800,
    "statusPembayaran": "1",
    "tglJatuhTempo": "2021-09-29T17:00:00.000+0000"
  }
]
----




== Data Ijmal Piutang dan Realisasi di Wilayah Tertentu Untuk Tahun Pajak Tertentu

Simpul ini memberikan informasi data rekapitulasi piutang dan realisasi untuk wilayah tertentu dan tahun pajak tertentu

=== _Endpoint_ dan _Methods_

----
POST /sismiop-service/desa/get-piutang-realisasi-by-wilayah-and-tahun
----

=== _Parameters_

==== _Request Parameters_

Objek dengan format JSON dengan elemen berikut :

* `kodeWilayah`: kode wilayah lengkap untuk Desa/Kelurahan, untuk Kecamatan, 3 (tiga) digit terakhir diisikan `000`, dan untuk Kabupaten, 6 (enam) digit terakhir diisikan `000000`
* `thnPajak`: tahun pajak

==== _Response Parameters_

* `piutang`: nilai total piutang untuk wilayah tersebut
* `realisasi`: nilai total realisasi untuk wilayah tersebut

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-piutang-realisasi-by-wilayah-and-tahun
----

_body_ :

----
{
    "kodeWilayah": "3329000000",
    "thnPajak": "2021"
}
----

=== _Response Example_

----
{
  "piutang": 29655587141,
  "realisasi": 13965437950
}
----



== Data Ijmal Piutang Untuk Wilayah Desa/Kelurahan Tertentu dan Tahun Pajak Tertentu

Simpul ini hanya memberikan data rekapitulasi piutang untuk wilayah Desa/Kelurahan tertentu dan tahun pajak tertentu

=== _Endpoint_ dan _Methods_ 

----
POST /sismiop-service/desa/get-piutang-by-desa-and-tahun
----

=== _Parameters_

==== _Request Parameters_

Objek dengan format JSON dengan elemen berikut :

* `kodeWilayah`: kode wilayah lengkap untuk Desa/Kelurahan
* `thnPajak`: tahun pajak

==== _Response Parameters_

Nilai piutang Pajak Bumi dan Bangunan Perdesaan dan Perkotaan

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-piutang-by-desa-and-tahun
----

_body_ : 

----
{
    "kodeWilayah": "3329160009",
    "thnPajak": "2021"
}
----

=== _Response Example_

----
377237142
----



== Data Ijmal Piutang Untuk Wilayah Tertentu dan Tahun Pajak Tertentu

Simpul ini hanya memberikan data rekapitulasi piutang untuk wilayah tertentu dan tahun pajak tertentu, wilayah Kabupaten/Kota, Kecamatan, dan Desa/Kelurahan akan dibedakan dari kode wilayahnya.

=== _Endpoint_ dan _Methods_

----
POST /sismiop-service/desa/get-piutang-by-kode-wilayah
----

=== _Parameters_

==== _Request Parameters_

Objek dengan format JSON dengan elemen berikut :

* `kodeWilayah`: kode wilayah lengkap untuk Desa/Kelurahan, untuk Kecamatan, 3 (tiga) digit terakhir diisikan `000`, dan untuk Kabupaten, 6 (enam) digit terakhir diisikan `000000`
* `thnPajak`: tahun pajak

==== _Response Parameters_

Nilai piutang Pajak Bumi dan Bangunan Perdesaan dan Perkotaan 

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-piutang-by-kode-wilayah
----

_body_ : 

----
{
    "kodeWilayah": "3329000000",
    "thnPajak": "2021"
}
----

=== _Response Example_

----
29637396276
----



== Data Ijmal Realisasi Untuk Wilayah Desa/Kelurahan Tertentu dan Tahun Pajak Tertentu

Simpul ini hanya memberikan nilai rekapitulasi realisasi untuk wilayah Desa/Kelurahan tertentu dan tahun pajak tertentu.

=== _Endpoint_ dan _Methods_

----
POST /sismiop-service/desa/get-realisasi-by-desa-and-tahun
----

=== _Parameters_

==== _Request Parameters_

Objek dengan format JSON dengan elemen berikut :

* `kodeWilayah`: kode wilayah lengkap untuk Desa/Kelurahan
* `thnPajak`: tahun pajak

==== _Response Parameters_

Nilai realisasi total untuk wilayah Desa/Kelurahan dengan tahun pajak tertentu

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-realisasi-by-desa-and-tahun
----

_body_ :

----
{
    "kodeWilayah": "3329010001",
    "thnPajak": "2021"
}
----

=== _response Example_

----
23942582
----



== Data Ijmal Realisasi Untuk Wilayah Tertentu dan Tahun Pajak Tertentu

Simpul ini hanya memberikan nilai rekapitulasi dari realisasi untuk wilayah tertentu dan tahun pajak tertentu. Wilayah Kabupaten/Kota, Kecamatan, dan Desa/Kelurahan akan dibedakan dari kode wilayahnya.

=== _Endpoint_ dan _Methods_

----
POST /sismiop-service/desa/get-realisasi-by-wilayah-and-tahun
----

=== _Parameters_

==== _Request Parameters_

Objek dengan format JSON dengan elemen berikut :

* `kodeWilayah`: kode wilayah lengkap untuk Desa/Kelurahan, untuk Kecamatan, 3 (tiga) digit terakhir diisikan `000`, dan untuk Kabupaten, 6 (enam) digit terakhir diisikan `000000`
* `thnPajak`: tahun pajak

==== _Response Parameters_

Nilai realisasi untuk wilayah tertentu dan tahun pajak tertentu

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-realisasi-by-wilayah-and-tahun
----

_body_ : 

----
{
    "kodeWilayah": "3329020000",
    "thnPajak": "2021"
}
----

=== _Response Example_

----
577133457
----



== Data Ijmal Ketetapan dan Realisasi Untuk Tiap Tahun Pajak Dalam Satu Kabupaten/Kota

Simpul ini memberikan informasi nilai ketetapan dan realisasi untuk setiap tahun pajak dalam wilayah Kabupaten/Kota

=== _Endpoint_ dan _Methods_

----
GET /sismiop-service/desa/get-resume-for-district
----

=== _Parameters_

==== _Request Parameters_

-

==== _Response Parameters_

`List` data yang berisi objek dengan elemen berikut :

* `thnPajak`: tahun pajak 
* `ketetapan`: besarnya ketetapan pajak untuk satu wilayah Kabupaten/Kota
* `realisasi`: besarnya realisasi pajak untuk satu wilayah Kabupaten/Kota

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-resume-for-district
----

=== _Response Example_

----
[
  {
    "thnPajak": "1994",
    "ketetapan": 32203,
    "realisasi": 79335
  },
  {
    "thnPajak": "1995",
    "ketetapan": 802356,
    "realisasi": 826966
  },
  {
    "thnPajak": "1996",
    "ketetapan": 10712717,
    "realisasi": 11192083
  },
  {
    "thnPajak": "1997",
    "ketetapan": 12474503,
    "realisasi": 13754524
  }
  ...
]
----



== Data Ijmal Ketetapan dan Realisasi Untuk Tiap Tahun Pajak Berdasarkan Kode Kecamatan

Simpul ini memberikan informasi nilai ketetapan dan realisasi tiap tahun pajak untuk wilayah Kecamatan tertentu

=== _Endpoint_ dan _Methods_

----
GET /sismiop-service/desa/get-resume-for-sub-district/{kdKecamatan}
----

=== _Parameters_

==== _Request Parameters_

`kdKecamatan` adalah 3 (tiga) digit kode Kecamatan

==== _Response Parameters_

`List` data yang berisi objek dengan elemen berikut :

* `thnPajak`: tahun pajak 
* `kdKecamatan`: 3 (tiga) digit kode Kecamatan
* `ketetapan`: besarnya ketetapan pajak untuk satu wilayah Kabupaten/Kota
* `realisasi`: besarnya realisasi pajak untuk satu wilayah Kabupaten/Kota

=== _Request Example_

----
http://pajak-daerah.brebeskab.go.id/sismiop-service/desa/get-resume-for-sub-district/010
----

=== _Response Example_

----
[
  {
    "thnPajak": "2004",
    "kdKecamatan": "010",
    "ketetapan": 32192663,
    "realisasi": 25823212
  },
  {
    "thnPajak": "2005",
    "kdKecamatan": "010",
    "ketetapan": 32938374,
    "realisasi": 33052508
  },
  {
    "thnPajak": "2006",
    "kdKecamatan": "010",
    "ketetapan": 33052947,
    "realisasi": 33052947
  },
  {
    "thnPajak": "2007",
    "kdKecamatan": "010",
    "ketetapan": 34273663,
    "realisasi": 34280913
  },
  ...
]
----

